### ISSUE TITLE
npm run dev not working

### ISSUE THREAD

**Issue by Arifi** [FAForever/clans#33]
Hi,
cmd output :

```
D:\fafdevelop\clans>npm run dev

> clanapp@1.0.0 dev D:\fafdevelop\clans
> webpack-dev-server --linline --content-base www

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1246:19)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! clanapp@1.0.0 dev: `webpack-dev-server --linline --content-base www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clanapp@1.0.0 dev script 'webpack-dev-server --linline --content-base www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the clanapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --linline --content-base www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs clanapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls clanapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\fafdevelop\clans\npm-debug.log
```

Note : I've changed server.js and set the port to 8085

I'm not node expert, so please let me know it i missed smth
Log file :
[npm-debug.log.txt](https://github.com/FAForever/clans/files/712032/npm-debug.log.txt)

**Comment by IDragonfire** [comment]
Can you join slack?
http://slackinvite.faforever.com/

**Comment by IDragonfire** [comment]
Did you run `npm install` before?

**Comment by Arifi** [comment]
yes,

i tryed `node server.js` and it worked

**Comment by IDragonfire** [comment]
The message above says, that something is allready running on the port `8080`

**Comment by Arifi** [comment]
I've changed server.js and set the port to 8085

**Comment by IDragonfire** [comment]
server.js is only for production server ...
add `--port 8085` in  https://github.com/FAForever/clans/blob/adf3cdf5a94261d61a619330af1447a0b8bd5879/package.json#L9

**Comment by Arifi** [comment]
Ok done, worked
